FROM node:11.12.0-alpine
RUN mkdir -p /app
WORKDIR /app

COPY package*.json /app/

RUN apk add --update --no-cache gifsicle ttf-freefont optipng libjpeg-turbo-utils udev chromium
RUN npm install -g @angular/cli@7.3.7
RUN npm install

ENV CHROME_BIN=/usr/bin/chromium-browser
RUN export CHROME_BIN=/usr/bin/chromium-browser
ENV LIGHTHOUSE_CHROMIUM_PATH=/usr/bin/chromium-browser
RUN export LIGHTHOUSE_CHROMIUM_PATH=/usr/bin/chromium-browser

COPY . /app

CMD ng serve --host 0.0.0.0 --disable-host-check=true

